# Site settings
title: TSLint
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://palantir.github.io/tslint/" # the base hostname & protocol for your site
twitter_username: PalantirTech
github_username:  palantir/tslint

# Build settings
markdown: redcarpet
markdown_ext: md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
