version: 2

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Check if lockfile changed
          command: git diff --exit-code
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn compile
      - persist_to_workspace:
          root: "."
          paths:
            - lib
            - build

  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn test

  test2.1:
    # note: testing old Node LTS here, see https://github.com/nodejs/Release
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@2.1
      - run: yarn test

  test2.4:
    # note: testing old Node LTS here, see https://github.com/nodejs/Release
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@2.4
      - run: yarn test

  test2.7:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@2.7
      - run: yarn test

  test2.8:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@2.8
      - run: yarn test

  test2.9:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@2.9
      - run: yarn test

  test3.0:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@3.0.1
      - run: yarn test

  testRc:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@rc
      - run: yarn test

  testNext:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn add typescript@next
      - run: yarn test

workflows:
  version: 2
  build_lint_test:
    jobs:
      - install_dependencies
      - build
          requires:
            - install_dependencies
      - lint:
          requires: [build]
      - test:
          requires: [build]
      - test2.1:
          requires: [build]
      - test2.4:
          requires: [build]
      - test2.7:
          requires: [build]
      - test2.8:
          requires: [build]
      - test2.9:
          requires: [build]
      - test3.0:
          requires: [build]
      - testRc:
          requires: [build]
      - testNext:
          requires: [build]
